[graph]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
all-features = true

[advisories]
yanked = "deny"
unmaintained = "workspace"
unsound = "all"
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "simplest-path"

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = false
unused = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Unicode-3.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
